import { useEffect, useMemo, useState } from "react";
import Modal from "../../components/ui/Modal";
import Button from "../../components/ui/Button";
import FormField,{inputClass} from "../../components/ui/FormField";
import PrintPreviewCanvas from "../../components/printing/PrintPreviewCanvas";
import { buildCommercialPrintHtml } from "../../utils/commercialPrintTemplate";
import { useLanguage } from "../../i18n/LanguageContext";
const formats=["A4","A5","THERMAL_80","THERMAL_58"];
export default function QuotePrintDialog({quote,onClose,setError}){const {t}=useLanguage();const [format,setFormat]=useState("A4"),[preview,setPreview]=useState(false);useEffect(()=>{if(quote){setFormat(quote.print_profile?.paper_format||"A4");setPreview(false);}},[quote]);const profile={...quote?.print_profile,document_type:"BON_POUR",paper_format:format,configuration:{...(quote?.print_profile?.configuration||{}),title:"DEVIS"}};const html=useMemo(()=>quote?buildCommercialPrintHtml(quote,profile):"",[quote,format]);async function print(){try{await window.electronAPI?.printDocument?.(quote,profile);onClose();}catch(e){setError(e.message);}}return <Modal open={!!quote} title={`Imprimer ${quote?.quote_number||""}`} onClose={onClose} width="xl" footer={preview?<><Button onClick={()=>setPreview(false)}>{t("back")}</Button><Button variant="primary" onClick={print}>{t("Imprimer")}</Button></>:<><Button onClick={onClose}>{t("Annuler")}</Button><Button onClick={print}>{t("Imprimer directement")}</Button><Button variant="primary" onClick={()=>setPreview(true)}>{t("Prévisualiser")}</Button></>}>{!preview?<div className="grid gap-4 p-5 sm:grid-cols-2"><FormField label={t("Document")}><input className={inputClass} value="Devis / Facture proforma" disabled/></FormField><FormField label={t("Format")}><select className={inputClass} value={format} onChange={e=>setFormat(e.target.value)}>{formats.map(x=><option key={x} value={x}>{x.replace("THERMAL_","Thermal ")}{x.startsWith("THERMAL")?" mm":""}</option>)}</select></FormField></div>:<div className="h-[65vh] min-h-0"><PrintPreviewCanvas html={html} format={format} title={t("Aperçu impression")}/></div>}</Modal>}
