const SETTING_DEFINITIONS = {
  "general.application_name": {
    type: "string",
    default: "POS Modern",
    pattern: /^.{1,80}$/,
  },
  "general.default_currency": {
    type: "string",
    default: "DZD",
    allowed: ["DZD", "EUR", "USD"],
  },
  "general.currency_display": {
    type: "string",
    default: "SYMBOL_AFTER",
    allowed: ["SYMBOL_AFTER", "CODE_AFTER", "CODE_BEFORE"],
  },
  "general.monetary_decimals": { type: "number", default: 2, min: 0, max: 4 },
  "general.date_format": {
    type: "string",
    default: "DD/MM/YYYY",
    allowed: ["DD/MM/YYYY", "YYYY-MM-DD", "MM/DD/YYYY"],
  },
  "general.time_format": {
    type: "string",
    default: "24H",
    allowed: ["24H", "12H"],
  },
  "general.product_images_enabled": { type: "boolean", default: false },
  "general.logo_data": { type: "string", default: null, nullable: true },
  "general.default_warehouse_id": { type: "number", default: null, nullable: true },
  "general.default_cash_register_id": { type: "number", default: null, nullable: true },
  "general.default_page_size": { type: "number", default: 25, min: 25, max: 100 },
  "general.confirm_destructive_actions": { type: "boolean", default: true },
  "sales.default_customer_id": {
    type: "number",
    default: null,
    nullable: true,
  },
  "sales.allow_default_customer": { type: "boolean", default: true },
  "sales.allow_negative_stock": { type: "boolean", default: false },
  "sales.allow_price_edit": { type: "boolean", default: false },
  "sales.allow_discount": { type: "boolean", default: true },
  "sales.quick_checkout_enabled": { type: "boolean", default: true },
  "sales.quick_checkout_payment_method": {
    type: "string",
    default: "DEFAULT",
    allowed: [
      "DEFAULT",
      "CASH",
      "CARD",
      "BANK_TRANSFER",
      "CHEQUE",
    ],
  },
  "sales.quick_checkout_exact_amount_only": { type: "boolean", default: true },
  "sales.max_discount_percent": {
    type: "number",
    default: 100,
    min: 0,
    max: 100,
  },
  "sales.scan_add_immediately": { type: "boolean", default: true },
  "sales.existing_product_behavior": {
    type: "string",
    default: "INCREMENT_QUANTITY",
    allowed: ["INCREMENT_QUANTITY", "NEW_LINE"],
  },
  "sales.default_fulfillment_type": {
    type: "string",
    default: "IMMEDIATE",
    allowed: ["IMMEDIATE", "SHIPPING"],
  },
  "sales.default_print_document": {
    type: "string",
    default: "TICKET",
    allowed: ["TICKET", "BON_POUR"],
  },
  "sales.default_print_format": {
    type: "string",
    default: "THERMAL_80",
    allowed: ["NONE", "A4", "A5", "THERMAL_80", "THERMAL_58"],
  },
  "purchases.default_print_format": {
    type: "string",
    default: "NONE",
    allowed: ["NONE", "A4", "A5", "THERMAL_80", "THERMAL_58"],
  },
  "payments.default_method": { type: "string", default: "CASH" },
  "invoicing.tax_enabled": { type: "boolean", default: true },
  "invoicing.tax_rate": { type: "number", default: 19, min: 0, max: 100 },
  "invoicing.stamp_enabled": { type: "boolean", default: true },
  "invoicing.stamp_rate": { type: "number", default: 1, min: 0, max: 100 },
  "cash.require_open_session_for_cash_payment": {
    type: "boolean",
    default: true,
  },
  "cash.block_negative_drawer": { type: "boolean", default: true },
  "cash.require_closing_count": { type: "boolean", default: true },
  "cash.require_difference_note": {
    type: "string",
    default: "WHEN_DIFFERENT",
    allowed: ["NEVER", "WHEN_DIFFERENT", "ALWAYS"],
  },
  "stock.low_stock_alert_enabled": { type: "boolean", default: true },
  "expiration.alert_enabled": { type: "boolean", default: true },
  "expiration.warning_days": { type: "number", default: 30, min: 1, max: 365 },
  "expiration.block_expired_sale": { type: "boolean", default: true },
  "expiration.warn_near_expiration": { type: "boolean", default: true },
  "expiration.use_fefo": { type: "boolean", default: true },
  "numbering.sale_prefix": {
    type: "string",
    default: "VNT",
    pattern: /^[A-Z0-9-]{1,10}$/,
  },
  "numbering.sale_include_year": { type: "boolean", default: true },
  "numbering.sale_padding": { type: "number", default: 6, min: 3, max: 10 },
  "printing.allow_format_override": { type: "boolean", default: true },
};
const GROUPS = {
  general: "general",
  sales: "sales",
  purchases: "purchases",
  payments: "payments",
  invoicing: "invoicing",
  cash: "cash",
  stock: "stock",
  expiration: "expiration",
  numbering: "numbering",
  printing: "printing",
};
module.exports = { SETTING_DEFINITIONS, GROUPS };
