const router = require("express").Router();
const controller = require("../controllers/settings.controller");
const auth = require("../middleware/auth.middleware");
router.use(auth);
router.get("/backups/list", controller.backups);
router.post("/backups/create", controller.createBackup);
router.post("/backups/upload", require("express").raw({ type: "application/octet-stream", limit: "512mb" }), controller.uploadBackup);
router.get("/backups/:name/download", controller.downloadBackup);
router.delete("/backups/:name", controller.deleteBackup);
router.post("/backups/:name/restore", controller.restoreBackup);
router.post("/data/reset", controller.resetBusinessData);
router.get("/payment-methods", controller.paymentMethods);
router.patch("/payment-methods/:code", controller.paymentStatus);
router.get("/printers", controller.printers);
router.post("/printers", controller.savePrinter);
router.get("/print-profiles", controller.profiles);
router.put("/print-profiles/:type", controller.saveProfile);
router.get("/:group", controller.group);
router.put("/:group", controller.updateGroup);
module.exports = router;
