const express = require("express");
const Controller = require("../controllers/unit.controller");
const authMiddleware = require("../middleware/auth.middleware");
const router = express.Router();
router.use(authMiddleware);
router.get("/", Controller.list);
router.post("/", Controller.create);
router.put("/:id", Controller.update);
router.patch("/:id/status", Controller.setStatus);
router.delete("/:id", Controller.remove);
module.exports = router;
