const assert=require("node:assert/strict");
const db=require("../config/database");
const Inventory=require("../services/inventory.service");

let complete=false;
try{db.transaction(()=>{
  const account=db.prepare("SELECT id FROM users ORDER BY id LIMIT 1").get();assert.ok(account,"A seeded user is required");
  const user={id:account.id,role:"admin",warehouse_id:null};
  const source=Number(db.prepare("INSERT INTO warehouses(name) VALUES(?)").run("Inventory Source").lastInsertRowid),destination=Number(db.prepare("INSERT INTO warehouses(name) VALUES(?)").run("Inventory Destination").lastInsertRowid),category=Number(db.prepare("INSERT INTO categories(name) VALUES(?)").run("Inventory Category").lastInsertRowid),baseUnit=Number(db.prepare("INSERT INTO units(name,symbol) VALUES(?,?)").run("Inventory Can","ican").lastInsertRowid),caseUnit=Number(db.prepare("INSERT INTO units(name,symbol) VALUES(?,?)").run("Inventory Case","icase").lastInsertRowid);
  const product=Number(db.prepare("INSERT INTO products(designation,category_id,unit_id,track_stock,min_stock) VALUES(?,?,?,?,?)").run("Inventory Cola",category,baseUnit,1,12).lastInsertRowid);
  const base=Number(db.prepare("INSERT INTO product_units(product_id,unit_id,conversion_factor,purchase_price,selling_price,is_base,is_active) VALUES(?,?,?,?,?,?,?)").run(product,baseUnit,1,10,15,1,1).lastInsertRowid),pack=Number(db.prepare("INSERT INTO product_units(product_id,unit_id,conversion_factor,purchase_price,selling_price,is_base,is_active) VALUES(?,?,?,?,?,?,?)").run(product,caseUnit,24,200,300,0,1).lastInsertRowid);
  const received=Inventory.receiveStock({warehouse_id:source,product_id:product,product_unit_id:pack,quantity:10,note:"delivery"},user);assert.equal(received.quantity,240);assert.equal(db.prepare("SELECT quantity FROM product_stock WHERE product_id=? AND warehouse_id=?").get(product,source).quantity,240);assert.equal(db.prepare("SELECT quantity FROM stock_movements WHERE product_id=? AND type='RECEIPT'").get(product).quantity,240);
  Inventory.adjustStock({warehouse_id:source,product_id:product,product_unit_id:base,quantity:5,direction:"out",note:"damage"},user);assert.equal(db.prepare("SELECT quantity FROM product_stock WHERE product_id=? AND warehouse_id=?").get(product,source).quantity,235);
  const transfer=Inventory.transferStock({source_warehouse_id:source,destination_warehouse_id:destination,product_id:product,product_unit_id:pack,quantity:2},user);assert.equal(transfer.quantity,48);assert.equal(db.prepare("SELECT quantity FROM product_stock WHERE product_id=? AND warehouse_id=?").get(product,source).quantity,187);assert.equal(db.prepare("SELECT quantity FROM product_stock WHERE product_id=? AND warehouse_id=?").get(product,destination).quantity,48);const pair=db.prepare("SELECT type,quantity FROM stock_movements WHERE reference_id=? ORDER BY type").all(transfer.reference_id);assert.equal(pair.length,2);assert.equal(pair.reduce((sum,row)=>sum+row.quantity,0),0);
  assert.throws(()=>Inventory.adjustStock({warehouse_id:source,product_id:product,product_unit_id:base,quantity:999,direction:"out"},user),/Insufficient stock/);assert.equal(db.prepare("SELECT quantity FROM product_stock WHERE product_id=? AND warehouse_id=?").get(product,source).quantity,187);
  const stockPage=Inventory.listStock({warehouseId:source,page:1,limit:25,status:"all",search:"Inventory Cola"},user);assert.equal(stockPage.items.length,1);assert.equal(stockPage.items[0].quantity,187);
  assert.equal(Inventory.listProducts("Inventory Cola",user,source)[0].product_units.length,2);
  const history=Inventory.listMovements({warehouseId:source,page:1,limit:25,productId:product,type:null,from:null,to:null},user);assert.equal(history.movements.length,3);
  const medicine=Number(db.prepare("INSERT INTO products(designation,category_id,unit_id,track_stock,track_batches,track_expiration,has_expiration) VALUES(?,?,?,?,?,?,?)").run("Inventory Medicine",category,baseUnit,1,1,1,1).lastInsertRowid),medicineUnit=Number(db.prepare("INSERT INTO product_units(product_id,unit_id,conversion_factor,purchase_price,selling_price,is_base,is_active) VALUES(?,?,?,?,?,?,?)").run(medicine,baseUnit,1,1,2,1,1).lastInsertRowid);
  Inventory.receiveStock({warehouse_id:source,product_id:medicine,product_unit_id:medicineUnit,quantity:100,batch_number:"LOT-A",expiration_date:"2028-05-31"},user);const sourceBatch=db.prepare("SELECT * FROM stock_batches WHERE product_id=? AND warehouse_id=?").get(medicine,source);assert.equal(sourceBatch.quantity,100);
  Inventory.transferStock({source_warehouse_id:source,destination_warehouse_id:destination,product_id:medicine,product_unit_id:medicineUnit,quantity:40,batch_id:sourceBatch.id},user);const destinationBatch=db.prepare("SELECT * FROM stock_batches WHERE product_id=? AND warehouse_id=?").get(medicine,destination);assert.equal(destinationBatch.batch_number,"LOT-A");assert.equal(destinationBatch.expiration_date,"2028-05-31");assert.equal(destinationBatch.quantity,40);
  complete=true;throw new Error("ROLLBACK_TEST");
})();}catch(error){if(error.message!=="ROLLBACK_TEST")throw error;}
assert.equal(complete,true);console.log("Inventory integration test passed (transaction rolled back).");
